#%RAML 0.8
title:     EVE Overseer
version:   v1
baseUri:   http://example.com/api
mediaType: application/json

securitySchemes:
  - http_basic:
      description: Http Basic Authentification
      type: "Basic Authentication"
  - token:
      description: Bearer Token Based Authentification
      type: "x-bearer-token"

/account:
  post:
    description: Create a new user
    body:
      application/json:
        example: |
          {
            "email": "john@example.com",
            "username": "John Doe",
            "password": "super_secret"
          }
    responses:
      200:
        body:
          example: |
            {
              "_id":      5416d356205631a938b8c967,
              "username": "John Doe",
              "email":    "john@example.com",
              "avatar":   "https://gravatar.com/avatar/74d17098589adafe4e08b2a132e768d75?s=120&d=identicon"
            }

  get:
    description: Get current user info
    securedBy: [ http_basic ]
    responses:
      200:
        body:
          example: |
            {
              "_id":      5416d356205631a938b8c967,
              "username": "john",
              "email":    "john@example.com",
              "avatar":   "https://gravatar.com/avatar/74d17098589adafe4e08b2a132e768d75?s=120&d=identicon"
            }

  put:
    description: Update user profile
    securedBy: [ http_basic ]
    body:
      application/json:
        example: |
          {
            "password": "new_password"
          }
    responses:
      200:
        body:
          example: |
            {
              "_id":      5416d356205631a938b8c967,
              "username": "John Doe",
              "email":    "john@example.com",
              "avatar":   "https://gravatar.com/avatar/74d17098589adafe4e08b2a132e768d75?s=120&d=identicon"
            }

  delete:
    description: Delete permanently the user
    securedBy: [ http_basic ]

/apikeys:

  get:
    description: Get list of apikeys
    securedBy: [ http_basic ]

  post:
    description: Add a new EVE Online ApiKey
    securedBy: [ http_basic ]
    body:
      application/json:
        example: |
          {
            "keyId": "123456",
            "verificationCode": "123456789123aze456sdf78989987sdfsdf",
          }
    responses:
      200:
        body:
          example: |
            {
              "keyId":            "123456",
              "verificationCode": "123456789123aze456sdf78989987sdfsdf",
              "accessMask":        1234567,
              "characters":        [
                "541dd56205631a938b8c967",
                "541dd56205631a938b8ccd7"
              ],
            }

  delete:
    description: Delete an ApiKey
    securedBy: [ http_basic ]


/characters:

  get:
    description: Get a list of characters
    securedBy: [ http_basic ]
    responses:
      200:
        body:
          example: |
            [
              {
                "id":       1365215823,
                "name":     "Alexis Prey",
                "corporation": {
                  "id":   238510404,
                  "name": "Puppies To the Rescue"
                },
                "alliance": {
                  "id":   9999,
                  "name": "Eve-ID Puppies Inc."
                },
                "faction": {
                  "id":   666,
                  "name": "Eve-ID Faction"
                },
                "picture":  "http://img.eveonline.com/avatar/001_512.jpg"
              },
              {
                "id":       2,
                "name":     "Jane Doe",
                "picture":  "http://img.eveonline.com/avatar/002_512.jpg"
              }
            ]

  /{characterId}:

    get:
      description: Get detailed informations for a character
      securedBy: [ http_basic ]
      responses:
        200:
          body:
            example: |
              {
                "id":          1365215823,
                "name":        "Alexis Prey",
                "corporation": {
                  "id":   238510404,
                  "name": "Puppies To the Rescue"
                },
                "alliance": {
                  "id":   9999,
                  "name": "Eve-ID Puppies Inc."
                },
                "faction": {
                  "id":   666,
                  "name": "Eve-ID Faction"
                },
                "birthdate":   "2006-01-01 00:00:00",
                "race":        "Minmatar",
                "bloodline":   "Brutor",
                "ancestry":    "Slave Child",
                "clone": {
                    "name":        "Clone Grade Pi",
                    "skillPoints": 54600000
                },
                "attributes": {
                  "intelligence" : {
                    "value": 6,
                    "enhancer": {
                      "name": "Memory Augmentation - Basic",
                      "value": 3
                    }
                  },
                  "memory" : {
                    "value": 4,
                    "enhancer": {
                      "name": "Memory Augmentation - Basic",
                      "value": 3
                    }
                  },
                  "charisma" : {
                    "value": 7,
                    "enhancer": {
                      "name": "Limited Social Adaptation Chip",
                      "value": 1
                    }
                  },
                  "perception" : {
                    "value": 12,
                    "enhancer": {
                      "name": "Ocular Filter - Basic",
                      "value": 3
                    }
                  },
                  "willpower" : {
                    "value": 10,
                    "enhancer": {
                      "name": "Neural Boost - Basic",
                      "value": 3
                    }
                  }
                },
                "balance":     "190210393.87",
                "gender":      "Male",
                "picture":     "http://img.eveonline.com/avatar/001_512.jpg"
              }

    /skills:

      get:
        description: Get list of skills
        securedBy: [ http_basic ]
        queryParameters:
          queued:
            description: Filter for skill queue only
            type:        boolean
            default:     false
        responses:
          200:
            body:
              example: |
                [
                  {
                    "id":          266,
                    "name":        "Corporation Management",
                    "skills": [
                      {
                        "id":          1235,
                        "name":        "Mechanics",
                        "description": "Skill at maintaining the mechanical components and structural integrity of a spaceship. 5% bonus to structure hit points per skill level."
                        "rank":        1
                        "level":       5
                        "points":      123485
                      },
                      {
                        "id":          2345
                        "name":        "Explosive Armor Compensation"
                        "description": "5% bonus to explosive resistance per level for Armor Coatings and Energized Platings"
                        "rank":        2
                        "level":       3
                        "points":      1234
                      }
                    ]
                  }
                ]
